/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "dark-blue": "#4f7982",
                "light-yellow": "#e8e6d0",
            },
            textColor: {
                "light-blue": "#d5e1e6",
                "light-yellow": "#e8e6d0",
                "yellow": "#eaea43",
            },
            backgroundColor: {
                "dark-blue": "#4f7982",
                "light-blue": "#d5e1e6",
                "mid-grey": "#575756",
                "dark-grey": "#2c2c2c",
                "extreme-light-grey": "#d2d2d2",
                "black": "#141414",
            },
            borderColor: {
                "light-blue": "#d5e1e6",
                "dark-blue": "#4f7982",
                "light-grey": "#8f8f8f",
                "dark-grey": "#555554",
                "light-black": "#585858",
            },
            fontFamily: {
                SFPro: ["SF-Pro", "SF-Pro"],
                SFProDisplayBold: ["SF-Pro-Display-Bold", "SF-Pro-Display-Bold"],
                SFProDisplayLight: ["SF-Pro-Display-Light", "SF-Pro-Display-Light"],
                SFProDisplayLightItalic: ["SF-Pro-Display-LightItalic", "SF-Pro-Display-LightItalic"],
                SFProDisplayMedium: ["SF-Pro-Display-Medium", "SF-Pro-Display-Medium"],
                SFProDisplayRegular: ["SF-Pro-Display-Regular", "SF-Pro-Display-Regular"],
                SFProDisplayRegularItalic: ["SF-Pro-Display-RegularItalic", "SF-Pro-Display-RegularItalic"],
                SFProDisplaySemibold: ["SF-Pro-Display-Semibold", "SF-Pro-Display-Semibold"],

                Countach: ["countach"],

                MollenBold: ["Mollen-Bold"],

                StratumBold: ["stratum-2-web-bold"],
                StratumMedium: ["stratum-2-web-medium"],
                StratumRegular: ["stratum-2-web-regular"],
            },
            backgroundImage: {
                "back_transporter": "url('/src/assets/images/transporter/back_transporter.png')",
                "back_transporter_1": "url('/src/assets/images/transporter/back_1.png')",
                "back_transporter_2": "url('/src/assets/images/transporter/back_2.png')",
                "back_transporter_3": "url('/src/assets/images/transporter/back_3.png')",
                "back_transporter_4": "url('/src/assets/images/transporter/back_4.png')",
                "back_transporter_5": "url('/src/assets/images/transporter/back_5.png')",
                "card": "url('/src/assets/images/transporter/card.png')",

                "social": "url('/src/assets/images/help/social.png')",

                "back_shop": "url('/src/assets/images/shop/background.png')",
                "bg_darkzone": "url('/src/assets/images/shop/bg_darkzone.png')",
                "back_profile": "url('/src/assets/images/profile/back_profile.png')",


                "back_store": "url('/src/assets/images/store/background.png')",
                "pass_1": "url('/src/assets/images/store/pass_1.png')",
                "pass_2": "url('/src/assets/images/store/pass_2.png')",
                "points": "url('/src/assets/images/store/points.png')",
                "100_points": "url('/src/assets/images/store/100_points.png')",
                "1100_points": "url('/src/assets/images/store/1100_points.png')",
                "2400_points": "url('/src/assets/images/store/2400_points.png')",
                "5000_points": "url('/src/assets/images/store/5000_points.png')",
                "9500_points": "url('/src/assets/images/store/9500_points.png')",
                "13000_points": "url('/src/assets/images/store/13000_points.png')",
                "21000_points": "url('/src/assets/images/store/21000_points.png')",
                "Caisse_Argent": "url('/src/assets/images/store/Caisse_Argent.png')",
                "Caisse_Bronze": "url('/src/assets/images/store/Caisse_Bronze.png')",
                "Caisse_Diamond": "url('/src/assets/images/store/Caisse_Diamond.png')",
                "Caisse_Or": "url('/src/assets/images/store/Caisse_Or.png')",

                "logo_redzone": "url('/src/assets/images/redzones/logo.png')",

                "xp_player": "url('/src/assets/images/store/xp_player.png')",
                "xp_team": "url('/src/assets/images/store/xp_team.png')",
                "xp_server": "url('/src/assets/images/store/xp_server.png')",

                "arrow": "url('/src/assets/images/shop/arrow.png')",
                "cross": "url('/src/assets/images/shop/cross.png')",

                "dev-bg": "url('/src/assets/images/dev-bg.png')",

                "back_kits": "url('/src/assets/images/kits/background.png')",
                "lock": "url('/src/assets/images/kits/lock.png')",
                "check": "url('/src/assets/images/kits/check.png')",
                "starter": "url('/src/assets/images/kits/starter.png')",
                "gold": "url('/src/assets/images/kits/gold.png')",
                "diamond": "url('/src/assets/images/kits/diamond.png')",
                "weekly": "url('/src/assets/images/kits/weekly.png')",
                "booster": "url('/src/assets/images/kits/booster.png')",

                "box": "url('/src/assets/images/inventory/items/box.png')",
                "box_back": "url('/src/assets/images/inventory/items/box_back.png')",
                "weapon_combatpistol": "url('/src/assets/images/inventory/items/weapon_combatpistol.png')",
                "weapon_tacticalrifle": "url('/src/assets/images/inventory/items/weapon_tacticalrifle.png')",
                "weapon_tacticalrifle2": "url('/src/assets/images/inventory/items/weapon_tacticalrifle2.png')",
                "weapon_carbinerifle2": "url('/src/assets/images/inventory/items/weapon_carbinerifle2.png')",
                "weapon_bullpuprifle2": "url('/src/assets/images/inventory/items/weapon_bullpuprifle2.png')",
                "weapon_carbinerifle_mk22": "url('/src/assets/images/inventory/items/weapon_carbinerifle_mk22.png')",
                "weapon_specialcarbine_mk22": "url('/src/assets/images/inventory/items/weapon_specialcarbine_mk22.png')",
                "weapon_militaryrifle2": "url('/src/assets/images/inventory/items/weapon_militaryrifle2.png')",
                "weapon_precisionrifle": "url('/src/assets/images/inventory/items/weapon_precisionrifle.png')",
                "weapon_advancedrifle": "url('/src/assets/images/inventory/items/weapon_advancedrifle.png')",
                "weapon_assaultrifle": "url('/src/assets/images/inventory/items/weapon_assaultrifle.png')",
                "weapon_carbinerifle": "url('/src/assets/images/inventory/items/weapon_carbinerifle.png')",
                "weapon_sniperrifle": "url('/src/assets/images/inventory/items/weapon_sniperrifle.png')",
                "weapon_heavyshotgun": "url('/src/assets/images/inventory/items/weapon_heavyshotgun.png')",
                "weapon_pumpshotgun": "url('/src/assets/images/inventory/items/weapon_pumpshotgun.png')",
                "weapon_assaultshotgun": "url('/src/assets/images/inventory/items/weapon_assaultshotgun.png')",
                "weapon_combatshotgun": "url('/src/assets/images/inventory/items/weapon_combatshotgun.png')",
                "weapon_heavysniper": "url('/src/assets/images/inventory/items/weapon_heavysniper.png')",
                "weapon_marksmanrifle": "url('/src/assets/images/inventory/items/weapon_marksmanrifle.png')",
                "weapon_specialcarbine": "url('/src/assets/images/inventory/items/weapon_specialcarbine.png')",
                "weapon_bullpuprifle": "url('/src/assets/images/inventory/items/weapon_bullpuprifle.png')",
                "weapon_microsmg": "url('/src/assets/images/inventory/items/weapon_microsmg.png')",
                "weapon_smg": "url('/src/assets/images/inventory/items/weapon_smg.png')",
                "weapon_assaultsmg": "url('/src/assets/images/inventory/items/weapon_assaultsmg.png')",
                "weapon_combatmg_mk2": "url('/src/assets/images/inventory/items/weapon_combatmg_mk2.png')",
                "weapon_gusenberg": "url('/src/assets/images/inventory/items/weapon_gusenberg.png')",
                "weapon_combatmg": "url('/src/assets/images/inventory/items/weapon_combatmg.png')",
                "weapon_combatmg2": "url('/src/assets/images/inventory/items/weapon_combatmg2.png')",
                "weapon_mg": "url('/src/assets/images/inventory/items/weapon_mg.png')",
                "weapon_combatpdw": "url('/src/assets/images/inventory/items/weapon_combatpdw.png')",
                "weapon_minismg": "url('/src/assets/images/inventory/items/weapon_minismg.png')",
                "weapon_appistol": "url('/src/assets/images/inventory/items/weapon_appistol.png')",
                "weapon_assaultrifle_mk2": "url('/src/assets/images/inventory/items/weapon_assaultrifle_mk2.png')",
                "weapon_autoshotgun": "url('/src/assets/images/inventory/items/weapon_autoshotgun.png')",
                "weapon_bat": "url('/src/assets/images/inventory/items/weapon_bat.png')",
                "weapon_bullpuprifle_mk2": "url('/src/assets/images/inventory/items/weapon_bullpuprifle_mk2.png')",
                "weapon_bullpupshotgun": "url('/src/assets/images/inventory/items/weapon_bullpupshotgun.png')",
                "weapon_carbinerifle_mk2": "url('/src/assets/images/inventory/items/weapon_carbinerifle_mk2.png')",
                "weapon_ceramicpistol": "url('/src/assets/images/inventory/items/weapon_ceramicpistol.png')",
                "weapon_compactrifle": "url('/src/assets/images/inventory/items/weapon_compactrifle.png')",
                "weapon_dbshotgun": "url('/src/assets/images/inventory/items/weapon_dbshotgun.png')",
                "weapon_emplauncher": "url('/src/assets/images/inventory/items/weapon_emplauncher.png')",
                "weapon_golfclub": "url('/src/assets/images/inventory/items/weapon_golfclub.png')",
                "weapon_heavypistol": "url('/src/assets/images/inventory/items/weapon_heavypistol.png')",
                "weapon_heavyrifle": "url('/src/assets/images/inventory/items/weapon_heavyrifle.png')",
                "weapon_heavysniper_mk2": "url('/src/assets/images/inventory/items/weapon_heavysniper_mk2.png')",
                "weapon_hominglauncher": "url('/src/assets/images/inventory/items/weapon_hominglauncher.png')",
                "weapon_marksmanpistol": "url('/src/assets/images/inventory/items/weapon_marksmanpistol.png')",
                "weapon_marksmanrifle_mk2": "url('/src/assets/images/inventory/items/weapon_marksmanrifle_mk2.png')",
                "weapon_militaryrifle": "url('/src/assets/images/inventory/items/weapon_militaryrifle.png')",
                "weapon_molotov": "url('/src/assets/images/inventory/items/weapon_molotov.png')",
                "weapon_musket": "url('/src/assets/images/inventory/items/weapon_musket.png')",
                "weapon_navyrevolver": "url('/src/assets/images/inventory/items/weapon_navyrevolver.png')",
                "weapon_pistol_mk2": "url('/src/assets/images/inventory/items/weapon_pistol_mk2.png')",
                "weapon_pistol50": "url('/src/assets/images/inventory/items/weapon_pistol50.png')",
                "weapon_pumpshotgun_mk2": "url('/src/assets/images/inventory/items/weapon_pumpshotgun_mk2.png')",
                "weapon_revolver_mk2": "url('/src/assets/images/inventory/items/weapon_revolver_mk2.png')",
                "weapon_revolver": "url('/src/assets/images/inventory/items/weapon_revolver.png')",
                "weapon_rpg": "url('/src/assets/images/inventory/items/weapon_rpg.png')",
                "weapon_sawnoffshotgun": "url('/src/assets/images/inventory/items/weapon_sawnoffshotgun.png')",
                "weapon_specialcarbine_mk2": "url('/src/assets/images/inventory/items/weapon_specialcarbine_mk2.png')",
                "weapon_smg_mk2": "url('/src/assets/images/inventory/items/weapon_smg_mk2.png')",

                "medikit": "url('/src/assets/images/inventory/items/medikit.png')",
                "bandage": "url('/src/assets/images/inventory/items/bandage.png')",

                "kevlar": "url('/src/assets/images/inventory/items/kevlar.png')",
                "kevlar2": "url('/src/assets/images/inventory/items/kevlar2.png')",
                "plate": "url('/src/assets/images/inventory/items/plate.png')",

                "crystal_speed": "url('/src/assets/images/inventory/items/crystal_speed.png')",
                "crystal_health": "url('/src/assets/images/inventory/items/crystal_health.png')",
                "crystal_camo": "url('/src/assets/images/inventory/items/crystal_camo.png')",
                "crystal_camo2": "url('/src/assets/images/inventory/items/crystal_camo2.png')",
                "crystal_boost": "url('/src/assets/images/inventory/items/crystal_boost.png')",

                "vehicle_paragon2": "url('/src/assets/images/inventory/items/vehicle_paragon2.png')",
                "vehicle_ruiner2": "url('/src/assets/images/inventory/items/vehicle_ruiner2.png')",
                "vehicle_nightshark": "url('/src/assets/images/inventory/items/vehicle_nightshark.png')",
                "vehicle_deluxo": "url('/src/assets/images/inventory/items/vehicle_deluxo.png')",
                "vehicle_oppressor": "url('/src/assets/images/inventory/items/vehicle_oppressor.png')",
                "vehicle_oppressor2": "url('/src/assets/images/inventory/items/vehicle_oppressor2.png')",
                "vehicle_scramjet": "url('/src/assets/images/inventory/items/vehicle_scramjet.png')",
                "vehicle_bmx": "url('/src/assets/images/inventory/items/vehicle_bmx.png')",

                "vehicle_buzzard2": "url('/src/assets/images/inventory/items/vehicle_buzzard2.png')",
                "vehicle_havok": "url('/src/assets/images/inventory/items/vehicle_havok.png')",
                "vehicle_club": "url('/src/assets/images/inventory/items/vehicle_club.png')",
                "vehicle_deathbike": "url('/src/assets/images/inventory/items/vehicle_deathbike.png')",
                "vehicle_mesa3": "url('/src/assets/images/inventory/items/vehicle_mesa3.png')",
                "vehicle_buffalo": "url('/src/assets/images/inventory/items/vehicle_buffalo.png')",
                "vehicle_savestra": "url('/src/assets/images/inventory/items/vehicle_savestra.png')",
                "vehicle_issi8": "url('/src/assets/images/inventory/items/vehicle_issi8.png')",
                "vehicle_brickade2": "url('/src/assets/images/inventory/items/vehicle_brickade2.png')",
                "vehicle_deity": "url('/src/assets/images/inventory/items/vehicle_deity.png')",
                "vehicle_flashgt": "url('/src/assets/images/inventory/items/vehicle_flashgt.png')",
                "vehicle_impaler2": "url('/src/assets/images/inventory/items/vehicle_impaler2.png')",
                "vehicle_dominator4": "url('/src/assets/images/inventory/items/vehicle_dominator4.png')",
                "vehicle_caracara2": "url('/src/assets/images/inventory/items/vehicle_caracara2.png')",
                "vehicle_everon": "url('/src/assets/images/inventory/items/vehicle_everon.png')",
                "vehicle_hellion": "url('/src/assets/images/inventory/items/vehicle_hellion.png')",
                "vehicle_dominator3": "url('/src/assets/images/inventory/items/vehicle_dominator3.png')",
                "vehicle_xls": "url('/src/assets/images/inventory/items/vehicle_xls.png')",
                "vehicle_scarab": "url('/src/assets/images/inventory/items/vehicle_scarab.png')",
                "vehicle_calico": "url('/src/assets/images/inventory/items/vehicle_calico.png')",
                "vehicle_contender": "url('/src/assets/images/inventory/items/vehicle_contender.png')",
                "vehicle_dukes2": "url('/src/assets/images/inventory/items/vehicle_dukes2.png')",
                "vehicle_elegy": "url('/src/assets/images/inventory/items/vehicle_elegy.png')",
                "vehicle_gauntlet4": "url('/src/assets/images/inventory/items/vehicle_gauntlet4.png')",
                "vehicle_insurgent2": "url('/src/assets/images/inventory/items/vehicle_insurgent2.png')",
                "vehicle_supervolito": "url('/src/assets/images/inventory/items/vehicle_supervolito.png')",
                "vehicle_thruster": "url('/src/assets/images/inventory/items/vehicle_thruster.png')",
                "vehicle_ztype": "url('/src/assets/images/inventory/items/vehicle_ztype.png')",
                "vehicle_vigilante": "url('/src/assets/images/inventory/items/vehicle_vigilante.png')",

                "addfriend": "url('/src/assets/images/friends/addfriend.png')",
                "invitefriend": "url('/src/assets/images/friends/invite.png')",
                "invitefriend2": "url('/src/assets/images/friends/invite2.png')",
                "background_friends": "url('/src/assets/images/friends/background_friends.png')",
                "background_invite": "url('/src/assets/images/friends/background_invite.png')",
                "goto": "url('/src/assets/images/friends/goto.png')",

                "newbie": "url('/src/assets/images/prestiges/prestige.gif')",
                "prestige_1": "url('/src/assets/images/prestiges/prestige_1.gif')",
                "prestige_2": "url('/src/assets/images/prestiges/prestige_2.gif')",
                "prestige_3": "url('/src/assets/images/prestiges/prestige_3.gif')",
                "prestige_4": "url('/src/assets/images/prestiges/prestige_4.gif')",
                "prestige_5": "url('/src/assets/images/prestiges/prestige_5.gif')",
                "prestige_6": "url('/src/assets/images/prestiges/prestige_6.gif')",
                "prestige_7": "url('/src/assets/images/prestiges/prestige_7.gif')",
                "prestige_8": "url('/src/assets/images/prestiges/prestige_8.gif')",
                "prestige_9": "url('/src/assets/images/prestiges/prestige_9.gif')",
                "top3kills": "url('/src/assets/images/prestiges/top3kills.gif')",
                "top3zombies": "url('/src/assets/images/prestiges/top3zombies.gif')",
                "top10kills": "url('/src/assets/images/prestiges/top10kills.gif')",
                "top10zombies": "url('/src/assets/images/prestiges/top10zombies.gif')",
                "nuke": "url('/src/assets/images/prestiges/nuke.gif')",
                "top3darkzone": "url('/src/assets/images/prestiges/top3darkzone.gif')",
                "top10darkzone": "url('/src/assets/images/prestiges/top10darkzone.gif')",

                "tag_profile": "url('/src/assets/images/profile/tag_profile.png')",
                "tag_id": "url('/src/assets/images/profile/tag_id.png')",
                "time_profile": "url('/src/assets/images/profile/time_profile.png')",
                "crew_profile": "url('/src/assets/images/profile/crew_profile.png')",
                "zombies_profile": "url('/src/assets/images/profile/zombies_profile.png')",
                "kills_profile": "url('/src/assets/images/profile/kills_profile.png')",
                "death_profile": "url('/src/assets/images/profile/death_profile.png')",
                "points_profile": "url('/src/assets/images/profile/points_profile.png')",
                "redzone_points_profile": "url('/src/assets/images/profile/redzone_points_profile.png')",
                "kd_profile": "url('/src/assets/images/profile/kd_profile.png')",

                "back_leaderboard": "url('/src/assets/images/leaderboard/background.png')",

                "back_squad": "url('/src/assets/images/squad/background.png')",

                "background_party": "url('/src/assets/images/party/background.png')",

                "lobby_0": "url('/src/assets/images/lobbies/lobby_0.png')",
                "lobby_1": "url('/src/assets/images/lobbies/lobby_1.png')",
                "lobby_2": "url('/src/assets/images/lobbies/lobby_2.png')",
                "lobby_3": "url('/src/assets/images/lobbies/lobby_3.png')",
                "lobby_4": "url('/src/assets/images/lobbies/lobby_4.png')",
                "lobby_5": "url('/src/assets/images/lobbies/lobby_5.png')",
                "ffa": "url('/src/assets/images/lobbies/ffa.png')",
                "tricks": "url('/src/assets/images/lobbies/tricks.png')",
                "aircraft": "url('/src/assets/images/lobbies/aircraft.png')",
                "redzones": "url('/src/assets/images/lobbies/redzones.png')",
                "global_world": "url('/src/assets/images/lobbies/global_world.png')",
                "background_modes": "url('/src/assets/images/lobbies/background_modes.png')",
                "main_logo_modes": "url('/src/assets/images/lobbies/main_logo_modes.png')",

                "background_banner": "url('/src/assets/images/banner/background_banner.png')",
                "calling_card_1": "url('/src/assets/images/banner/calling_cards/1.gif')",
                "calling_card_2": "url('/src/assets/images/banner/calling_cards/2.gif')",
                "calling_card_3": "url('/src/assets/images/banner/calling_cards/3.gif')",
                "calling_card_4": "url('/src/assets/images/banner/calling_cards/4.gif')",
                "calling_card_5": "url('/src/assets/images/banner/calling_cards/5.gif')",
                "calling_card_6": "url('/src/assets/images/banner/calling_cards/6.gif')",
                "calling_card_7": "url('/src/assets/images/banner/calling_cards/7.gif')",
                "calling_card_8": "url('/src/assets/images/banner/calling_cards/8.gif')",
                "calling_card_9": "url('/src/assets/images/banner/calling_cards/9.gif')",
                "calling_card_10": "url('/src/assets/images/banner/calling_cards/10.gif')",
                "calling_card_11": "url('/src/assets/images/banner/calling_cards/11.gif')",
                "calling_card_12": "url('/src/assets/images/banner/calling_cards/12.gif')",
                "calling_card_13": "url('/src/assets/images/banner/calling_cards/13.gif')",
                "calling_card_14": "url('/src/assets/images/banner/calling_cards/14.gif')",
                "calling_card_15": "url('/src/assets/images/banner/calling_cards/15.gif')",
                "calling_card_16": "url('/src/assets/images/banner/calling_cards/16.gif')",
                "calling_card_17": "url('/src/assets/images/banner/calling_cards/17.gif')",
                "calling_card_18": "url('/src/assets/images/banner/calling_cards/18.gif')",
                "calling_card_19": "url('/src/assets/images/banner/calling_cards/19.gif')",
                "calling_card_20": "url('/src/assets/images/banner/calling_cards/20.gif')",
                "calling_card_21": "url('/src/assets/images/banner/calling_cards/21.gif')",
                "calling_card_22": "url('/src/assets/images/banner/calling_cards/22.gif')",
                "calling_card_23": "url('/src/assets/images/banner/calling_cards/23.gif')",
                "calling_card_24": "url('/src/assets/images/banner/calling_cards/24.gif')",
                "calling_card_25": "url('/src/assets/images/banner/calling_cards/25.gif')",
                "calling_card_26": "url('/src/assets/images/banner/calling_cards/26.gif')",
                "calling_card_27": "url('/src/assets/images/banner/calling_cards/27.gif')",
                "calling_card_28": "url('/src/assets/images/banner/calling_cards/28.gif')",
                "calling_card_29": "url('/src/assets/images/banner/calling_cards/29.gif')",
                "calling_card_30": "url('/src/assets/images/banner/calling_cards/30.gif')",
                "calling_card_31": "url('/src/assets/images/banner/calling_cards/31.gif')",
                "calling_card_32": "url('/src/assets/images/banner/calling_cards/32.gif')",
                "calling_card_33": "url('/src/assets/images/banner/calling_cards/33.gif')",
                "calling_card_34": "url('/src/assets/images/banner/calling_cards/34.gif')",
                "calling_card_35": "url('/src/assets/images/banner/calling_cards/35.gif')",
                "calling_card_36": "url('/src/assets/images/banner/calling_cards/36.gif')",
                "calling_card_37": "url('/src/assets/images/banner/calling_cards/37.gif')",
                "calling_card_38": "url('/src/assets/images/banner/calling_cards/38.gif')",
                "calling_card_39": "url('/src/assets/images/banner/calling_cards/39.gif')",
                "calling_card_40": "url('/src/assets/images/banner/calling_cards/40.gif')",
                "calling_card_41": "url('/src/assets/images/banner/calling_cards/41.gif')",
                "calling_card_42": "url('/src/assets/images/banner/calling_cards/42.gif')",
                "calling_card_43": "url('/src/assets/images/banner/calling_cards/43.gif')",
                "calling_card_44": "url('/src/assets/images/banner/calling_cards/44.gif')",
                "calling_card_45": "url('/src/assets/images/banner/calling_cards/45.gif')",
                "calling_card_46": "url('/src/assets/images/banner/calling_cards/46.gif')",
                "calling_card_47": "url('/src/assets/images/banner/calling_cards/47.gif')",
                "calling_card_48": "url('/src/assets/images/banner/calling_cards/48.gif')",
                "calling_card_49": "url('/src/assets/images/banner/calling_cards/49.gif')",
                "calling_card_50": "url('/src/assets/images/banner/calling_cards/50.gif')",
                "calling_card_51": "url('/src/assets/images/banner/calling_cards/51.gif')",
                "calling_card_52": "url('/src/assets/images/banner/calling_cards/52.gif')",
                "calling_card_53": "url('/src/assets/images/banner/calling_cards/53.gif')",
                "calling_card_54": "url('/src/assets/images/banner/calling_cards/54.gif')",
                "calling_card_55": "url('/src/assets/images/banner/calling_cards/55.gif')",
                "calling_card_56": "url('/src/assets/images/banner/calling_cards/56.gif')",
                "calling_card_57": "url('/src/assets/images/banner/calling_cards/57.gif')",
                "calling_card_58": "url('/src/assets/images/banner/calling_cards/58.gif')",
                "calling_card_59": "url('/src/assets/images/banner/calling_cards/59.gif')",
                "calling_card_60": "url('/src/assets/images/banner/calling_cards/60.gif')",

                "background_trade": "url('/src/assets/images/trade/background.png')",

                "background_settings": "url('/src/assets/images/settings/background.png')",
                "settings": "url('/src/assets/images/settings/settings.png')",
                "settings_2": "url('/src/assets/images/settings/settings_2.png')",
                "news": "url('/src/assets/images/settings/news.png')",
                "news_2": "url('/src/assets/images/settings/news_2.png')",


                "background_bundle_1": "url('/src/assets/images/bundle/background_1.png')",
                "background_bundle_hunt": "url('/src/assets/images/bundle/hunt.png')",
                "background_bundle_demon_chains": "url('/src/assets/images/bundle/demon-chains.png')",
                "background_bundle_venom": "url('/src/assets/images/bundle/venom.png')",
            },
            dropShadow: {
                'kit_take': '0 -70px 50px rgba(121, 164, 173, 1)',
                'kit_see': '0 -70px 50px rgba(255, 255, 255, 1)',
                'leaderboard_player': '0 0px 7px rgba(213, 225, 230, 1)',
            },
            screens: {
                '800': '800px',
                '1024': '1024px',
                '1280': '1280px',
                '1440': '1440px',
                '1600': '1600px',
                '1920': '1920px',
                '2560': '2560px'
            },
        },
    },
    plugins: [],
}
